# Generated by Django 5.1.6 on 2025-07-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ytid', models.TextField(verbose_name='YouTube ID')),
                ('title', models.TextField(default='A Youtube Video', verbose_name='Video Title')),
                ('file', models.FileField(upload_to='media/videos/', verbose_name='Video File')),
            ],
        ),
    ]
