# Generated by Django 5.2.4 on 2025-07-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ytid', models.TextField(max_length=16, unique=True, verbose_name='YouTube ID')),
                ('title', models.TextField(default='A Youtube Video', max_length=128, verbose_name='Title')),
                ('description', models.TextField(default='No Description', max_length=5048, verbose_name='Description')),
                ('creation_date', models.DateTimeField(null=True, verbose_name='Became Available On')),
                ('view_count', models.PositiveBigIntegerField(default=0, verbose_name='View Count')),
                ('like_count', models.PositiveBigIntegerField(default=0, verbose_name='Like Count')),
                ('availability', models.TextField(default='public', max_length=16, verbose_name='Video Availability')),
                ('channel', models.TextField(max_length=64, null=True, verbose_name="Video's Channel")),
                ('channel_url', models.TextField(max_length=128, null=True, verbose_name='URL of the Channel')),
                ('file', models.FileField(null=True, upload_to='videos/', verbose_name='Video File')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Time of Request')),
                ('status', models.SmallIntegerField(choices=[(0, 'pending'), (1, 'complete'), (2, 'failed')], default=0, verbose_name='Video Status')),
            ],
        ),
    ]
