# Generated by Django 5.2.4 on 2025-07-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(default='No description', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='videos/', verbose_name='Video File'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.TextField(default='A Youtube Video', verbose_name='Title'),
        ),
    ]
