# Generated by Django 5.2.4 on 2025-07-21 06:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_description_alter_video_file_alter_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='availability',
            field=models.TextField(default='public', verbose_name='Video Status'),
        ),
        migrations.AddField(
            model_name='video',
            name='channel',
            field=models.TextField(default='NOT DEFINED', verbose_name="Video's Channel"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='channel_url',
            field=models.TextField(default='NO', verbose_name='URL of the Channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Became Available On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='dislike_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Dislike Count'),
        ),
        migrations.AddField(
            model_name='video',
            name='like_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Like Count'),
        ),
        migrations.AddField(
            model_name='video',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Time of Request'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='View Count'),
        ),
    ]
