# Generated by Django 5.2.4 on 2025-07-21 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_availability_video_channel_video_channel_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='dislike_count',
        ),
    ]
