# Generated by Django 5.2.4 on 2025-07-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_remove_video_dislike_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'pending'), (1, 'complete'), (2, 'failed')], default=0, verbose_name='Video Status'),
        ),
        migrations.AlterField(
            model_name='video',
            name='availability',
            field=models.TextField(default='public', verbose_name='Video Availability'),
        ),
        migrations.AlterField(
            model_name='video',
            name='channel',
            field=models.TextField(null=True, verbose_name="Video's Channel"),
        ),
        migrations.AlterField(
            model_name='video',
            name='channel_url',
            field=models.TextField(null=True, verbose_name='URL of the Channel'),
        ),
        migrations.AlterField(
            model_name='video',
            name='creation_date',
            field=models.DateTimeField(null=True, verbose_name='Became Available On'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(default='No Description', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='Video File'),
        ),
        migrations.AlterField(
            model_name='video',
            name='ytid',
            field=models.TextField(unique=True, verbose_name='YouTube ID'),
        ),
    ]
